Fix playbooks
kawazaki0/networking-opencontrail pull request #1
Opened 2018-04-06 16:53 UTC by pawelzny

Już wiem dlaczego w tym pull request jest tak dużo plików.

Pobrałem branch z Gerrit review i od niego zrobiłem swój branch.
W związku z tym kiedy teraz robię pull request do tego repozytorium to razem ze zmianami, które wrzuciłeś do review, ale nie wrzuciłeś ich do tego repo.

Jeśli zrobisz push zmian do brancha enable_plugin_fix to wtedy w tym pull request będzie widać tylko moją zmianę w playbooks.rst, bez Twoich zmian.

Mam nadzieję, że w miarę zrozumiale to napisałem.

2018-04-06 16:55 UTC, pawelzny commented on doc/source/installation/playbooks.rst
Nie napisałem, który plik należy edytować.

```
$ vim inventory/group_vars/container_hosts.yml
```

2018-04-10 14:19 UTC, kawazaki0 requested changes

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
>  +-----------+--------------+----------------+--------------+------------------------------------+
tabelka powinna pójść do kroku `1. Prepare machines for `

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +    $ ssh contrail-node
tu trzeba używać już ipków z tej tabelki

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +    $ sudo apt install ansible
trzeba dodać jeszcze, że nasze playbooki wymagają apt install python-netaddr lub pip install netaddr, ale nie wiem które działa :)

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +**1. Prepare machines for Contrail (CentOS) node and OpenStack (Ubuntu) node.**
jeśli tabelka się pojawi w tym kroku, to nie trzeba tych nawiasów z nazwą OSa

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +branches but it is highly recommended to use only stable branches.
``openstack_branch`` should be set to ``stable/ocata``
``contrail_branch`` is currently ignored but it must not be empty.

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +    openstack_ip: 192.168.0.8
IPki muszą zgadzać się z tabelką

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +          plugin also should point to ``stable/ocata`` branch.
IMO to powinno pójść na koniec tego punktu. Najpierw trzeba pokazać jak to włączyć w wersji stable/ocata, a później dodać tą notatkę, że ma się zgadzać z openstackiem. A to dlatego, że openstacka też rekomendowaliśmy stable/ocata i nie ma tu żadnych decyzji do podjęcia dla czytającego

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +    $ ./main.yml --limit=openstack
jeśli playbooki się zmienią i będą deployować coś na host contraila, to trzeba wywalić ten --limit

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +Or in case shebang has not been correctly recognized
przecież w repozytorium plik main ma poprawny shebang i ma prawa execute :). IMO to jest niepotrzebne

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +``contrail_ip`` and ``openstack_ip`` should be local IP addresses.
niekonsekwencja z tabelką i linią 173:
> internal IP of contrail node

albo internal albo local.

2018-04-10 14:19 UTC, kawazaki0 commented on doc/source/installation/playbooks.rst
> +      CONTROLLER_NODES: 192.168.0.2  # contrail node local IP
local czy internal?

2018-04-11 06:51 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +    $ sudo apt install ansible
`python-netaddr` jest instalowany jako dependency do czegośtam. Ja tego nie instalowałem manualnie. Jednak warto dopisać na wszelki wypadek. 

Natomiast to co jest wymagane to Ansible >=2.5, a w domyślnym PPA Ubuntu jest wersja 2.0 więc napiszę jak zainstalować najnowszą wersję.

2018-04-11 06:56 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +Or in case shebang has not been correctly recognized
To prawda, nie potrzebne. Tylko trzeba poprawić path bo zły wpisałem.
Założyłem, że ktoś będzie miał PWD ustawione na folder playbooks, a nie musi tak być.

2018-04-11 07:04 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +**1. Prepare machines for Contrail (CentOS) node and OpenStack (Ubuntu) node.**
ok

2018-04-11 07:05 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +branches but it is highly recommended to use only stable branches.
ok

2018-04-11 07:06 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +    openstack_ip: 192.168.0.8
ok

2018-04-11 07:09 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +    $ ./main.yml --limit=openstack
ok

2018-04-11 07:10 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +``contrail_ip`` and ``openstack_ip`` should be local IP addresses.
ok. Zmieniłem wszystko na Internal, tak jak jest w tabelce.
Btw. to sa praktycznie synonimy ale masz racje, niech bedzie spójnie.

2018-04-11 07:10 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +      CONTROLLER_NODES: 192.168.0.2  # contrail node local IP
ok

2018-04-11 07:10 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +    $ ssh contrail-node
ok

2018-04-11 07:10 UTC, pawelzny commented on doc/source/installation/playbooks.rst
>  +-----------+--------------+----------------+--------------+------------------------------------+
ok

2018-04-11 07:12 UTC, pawelzny commented on doc/source/installation/playbooks.rst
> +          plugin also should point to ``stable/ocata`` branch.
ok

2018-04-24 14:57 UTC, closed without merging